### ISSUE TITLE
能不能修改下关于留空白页的地方

### ISSUE THREAD

**Issue by TillLindemann** [zhangchuheng123/NJUThesis#1]
您说留空白页是为了每个大章起始页数为偶数，但是不光我的大章不是以偶数页起始的，还会导致丢失页码，比如第一章在第一页，第二章就会在第三页，中间会缺失第二页，我不知道这样能不能通过教务处，但是我觉得这样可能真的是有问题的，然而我也不知道如何修改您的cls文件（latex小白），所以能不能删掉关于留白的内容。

**Comment by zhangchuheng123** [comment]
The related command to control inserted blank pages is a user defined command `\cleardoublepage` on line 507 of `njuthesis.cls`. If you do not want to insert additional empty page, you can change all the `\cleardoublepage` to `\clearpage`. Specifically, they are located in line 804, 877, 903, 958 and 989 currently.
